### ISSUE TITLE
Where to add the new chat color to resolve the error

### ISSUE THREAD

**Issue by DanteRedrum** [marcostom32/chat-design#1]
I'm sorry but I didn't understand where to enter that snippet of code. 
I assume its somewhere in chat but couldn't find a TriggerEvent for it like the code shows.
I am using the standard QBCore template.

Thank you!

**Comment by izmystic** [comment]
tell me command and ill post the fix

**Comment by DanteRedrum** [comment]
Same or similar issue to error #2

**Comment by wickednz** [comment]
```lua
sv_chat.lua

AddEventHandler('playerJoining', function()
    if GetConvarInt('chat_showJoins', 1) == 0 then
        return
    end
    local color = 255, 255, 255
    TriggerClientEvent('chatMessage', -1, 'SERVERNAMEHERE', color, '^2*' .. GetPlayerName(source) .. ' joined.')
  
end)

AddEventHandler('playerDropped', function(reason)
    if GetConvarInt('chat_showQuits', 1) == 0 then
        return
    end

    local color = 255, 255, 255
    TriggerClientEvent('chatMessage', -1, 'SERVERNAMEHERE', color, '^2*' .. GetPlayerName(source) ..' left (' .. reason .. ')')

end)
```

**Comment by DanteRedrum** [comment]
This was able to resolve my issue. I originally added it to the cl_chat.lua  and I added it incorrectly because I did local color = {255, 255, 255} adding it to the sv_chat.lua and removing the error I created in my poor attempt to follow the instruction fixed this issue. 
Thank you very much!
