### ISSUE TITLE
Attempt to concatenate a table value (local 'color')

### ISSUE THREAD

**Issue by Krizmatic** [marcostom32/chat-design#2]
It shows when we connect to the server. I have read the readme, tried doing the same. It didn't help. It will be better if you can show a sample.

**Comment by marcostom32** [comment]
add the color field in the chat:addmessage trigger

**Comment by wickednz** [comment]
```lua
sv_chat.lua

AddEventHandler('playerJoining', function()
    if GetConvarInt('chat_showJoins', 1) == 0 then
        return
    end
    local color = 255, 255, 255
    TriggerClientEvent('chatMessage', -1, 'SERVERNAMEHERE', color, '^2*' .. GetPlayerName(source) .. ' joined.')
  
end)

AddEventHandler('playerDropped', function(reason)
    if GetConvarInt('chat_showQuits', 1) == 0 then
        return
    end

    local color = 255, 255, 255
    TriggerClientEvent('chatMessage', -1, 'SERVERNAMEHERE', color, '^2*' .. GetPlayerName(source) ..' left (' .. reason .. ')')

end)
```

**Comment by Krizmatic** [comment]
> ```lua
> sv_chat.lua
> 
> AddEventHandler('playerJoining', function()
>     if GetConvarInt('chat_showJoins', 1) == 0 then
>         return
>     end
>     local color = 255, 255, 255
>     TriggerClientEvent('chatMessage', -1, 'SERVERNAMEHERE', color, '^2*' .. GetPlayerName(source) .. ' joined.')
>   
> end)
> 
> AddEventHandler('playerDropped', function(reason)
>     if GetConvarInt('chat_showQuits', 1) == 0 then
>         return
>     end
> 
>     local color = 255, 255, 255
>     TriggerClientEvent('chatMessage', -1, 'SERVERNAMEHERE', color, '^2*' .. GetPlayerName(source) ..' left (' .. reason .. ')')
> 
> end)
> ```

Thanks a lot
